version: '3'
services:
  api:
    container_name: api
    build:
      - ./api
    ports:
      - 3000:3000
    depends_on:
      - mongod
  web:
    container_name: web
    build:
      - ./web
    volumes:
      - ./web/:/etc/nginx/conf.d/
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
      - 28017:28017
