version: '3'
services:
  api:
    container_name: 'api'
    build: './api'
    ports:
      - '8080:8080'
    volumes:
      - './api:$GOPATH/src&github.com/kongebra/cpts/api'
    depends_on:
      - 'mongo'
  web:
    container_name: 'web'
    build: './web'
    ports:
      - '8081:80'
    volumes:
      - './web:/usr/share/nginx/html'
    depends_on:
      - 'api'
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - '27100:27017'