version: '3'
services:
  api:
    image: golang:1.11.2
    networks:
      - mongo-go
      - nginx-go
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  nginx:
    image: nginx
    volumes:
      - /etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    networks:
      - nginx-go
    depends_on:
      - api
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  mongodb:
    image: mongo
    volumes:
      - mongodb-data:/data/db
    networks:
      - mongo-go
    ports:
      - 27017:27017
      - 28017:28017
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  networks:
    mongo-go:
    nginx-go:
  volumes:
    mongodb-data: