version: '3'
services:
  api:
    image: golang:onbuild
    container_name: api
    build: ./api
    ports:
      - 3000:3000
    volumes:
      - .:/api
    environment:
      - PORT=3000
    depends_on:
      - mongo
  web:
    image: nginx
    container_name: web
    build: ./web
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/web
    depends_on:
      - api
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017