version: '3'
services:
  app-back:
    image: cpts/api
    networks:
      - mongo-go
      - nginx-go
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  nginx:
    image: cpts/web
    volumes:
      - /etc/nginx/conf.d/
    ports:
      - 80:80
      - 443:443
    networks:
      - nginx-go
    depends_on:
      - app-back
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  mongodb:
    image: cpts/mongodb
    volumes:
      - mongodb-data:/data/db
    networks:
      - mongo-go
    ports:
      - 27017:27017
      - 28017:28017
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
