cnf ?= config.env
include $(cnf)
export $(shell sed 's/=.*//' $(cnf))

dpl ?= deploy.env
include $(dpl)
export $(shell sed 's/=.*//' $(dpl))

build:
    docker-compose build --no-cache $(APP_NAME)
    docker-compose run $(APP_NAME) grunt build
    docker build -t $(APP_NAME)

run:
    docker run -i -t --rm --env-file=./config.env -p=$(PORT):$(PORT) --name="$(APP_NAME)" $(APP_NAME)