version: '3'
services:
  api:
    build: ./api
    image: cpts/api
    ports:
      - 3000:3000
    depends_on:
      - mongo
  nginx:
    build: ./web
    image: cpts/web
    ports:
      - 80:80
    depends_on:
      - api
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017